In [1]:
import pandas as pd

In [33]:
df = pd.read_csv('inverts_database_CSV.csv', encoding = "ISO-8859-1", engine='python')

In [42]:
#look at the data set
pd.set_option('display.max_columns', 50)
df.head()

,the_source,country,region,sitename,Lat,Lon,Year,Date,depth_m,common name,Phylum,Class,Order,Family,Genus,genus species,Count,transect,t_Length,t_Width,Transect_area,total number of transect,total transect area,den_per_100m2,den_for_transect_#permeter,density_for_summed_transect area_#permeter,den_per_HA,id
0,LTO,Mozambique,Komame,Pao,-24.067983,35.053267,2016.0,8-Aug-16,17.7,Granular starfish,Echinodermata,Asteroidea,Valvatida,Oreasteridae,Choriaster,Austrofromia schultzei,1,1,80.0,5,400,1.0,400.0,NaN,0.0025,NaN,NaN,1
1,LTO,Mozambique,Komame,Pao,-24.067983,35.053267,2016.0,1-Sep-16,16,Longspined Sea Urchin,Echinodermata,Echinoidea,Diadematoida,Diadematidae,Diadema,Diadema setosum,38,1,80.0,5,400,1.0,400.0,NaN,0.095,NaN,NaN,2
2,LTO,Mozambique,Komame,Neptune,-24.066992,35.503783,2016.0,1-Sep-16,16,Magnificent Anemone,Cnidaria,Anthozoa,Actiniaria,Stichodactylidae,Heteractis,Heteractic mangnifica,2,1,80.0,5,400,1.0,400.0,NaN,0.005,NaN,NaN,3
3,LTO,Mozambique,Komame,Neptune,-24.066992,35.503783,2016.0,1-Sep-16,16,Blue Starfish,Echinodermata,Asteroidea,Valvatida,Ophidiasteridae,Linckia,Linckia laevigata,1,1,80.0,5,400,1.0,400.0,NaN,0.0025,NaN,NaN,4
4,LTO,Mozambique,Komame,Neptune,-24.066992,35.503783,2016.0,10-Aug-16,17.7,Giant Anemone,Cnidaria,Anthozoa,Actiniaria,Actiniidae,Condylactis,Heteractis magnifica,7,1,80.0,5,400,1.0,400.0,NaN,0.0175,NaN,NaN,5

In [34]:
#remove some unnecessary columns
df = df.drop(["Abundance","Method","Ecoregion","habitat_type","management"], axis=1)

In [16]:
#check present columns
for col in df.columns: 
    print(col)

the_source
Ecoregion
country
region
sitename
Lat
Lon
management
Year
Date
habitat_type
depth_m
common name
Phylum
Class
Order
Family
Genus
genus species
Count
transect
t_Length
t_Width
Transect_area
total number of transect
total transect area
den_per_100m2
den_for_transect_#permeter
density_for_summed_transect area_#permeter
den_per_HA

In [36]:
#make sure a dataframe
df = pd.DataFrame(df)

In [37]:
#add a unique id beyond index
df["id"] = df.index + 1

In [43]:
#look at data sources to select a target 
df.the_source.unique()

array(['LTO', 'MB_echin', 'MB_molls', 'MB_urchin', 'RMI_09_10', 'RMI_ail',
       'RMI_Ailk_06', 'RMI_bik_02_03', 'SPC', 'RC_Indo', 'RC_ARB',
       'RC_ATL', 'RC_EST', 'RC_HAW', 'RC_RED', 'RLS', 'NOAA_MMT',
       'NOAA_PR_1999_2003', 'NOAA_PR_2004_2013', 'NOAA_PR_2014_2018',
       'NOAA_Tortugas', 'KW_Jap', 'Leeds_mart', 'CCC_C', 'CCC_M', 'CCC_P',
       'ECOT', 'NOAA_Fen_08'], dtype=object)

In [48]:
#test of adding absence data with just ccc_c first

CCC = df['the_source'] == "CCC_C"
dfc = df[CCC]

In [50]:
dfc.head(10)

,the_source,country,region,sitename,Lat,Lon,Year,Date,depth_m,common name,Phylum,Class,Order,Family,Genus,genus species,Count,transect,t_Length,t_Width,Transect_area,total number of transect,total transect area,den_per_100m2,den_for_transect_#permeter,density_for_summed_transect area_#permeter,den_per_HA,id
175735,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175736
175736,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,19,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175737
175737,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175738
175738,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175739
175739,CCC_C,Cambodia,KK01,KK01,10.63664776,103.3009767,2010.0,5/9/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,16,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175740
175740,CCC_C,Cambodia,KK01,KK01,10.63664776,103.3009767,2010.0,5/9/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,28,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175741
175741,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,48,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175742
175742,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,69,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175743
175743,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,107,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175744
175744,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,78,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,175745

In [58]:
#import target species data
TS = pd.read_csv('target_species.csv', encoding = "ISO-8859-1", engine='python')
TS = TS.CCC_C
TS = pd.DataFrame(TS)
TS.head(18)

                     CCC_C
0     Feather Duster Worms
1     Christmas Tree Worms
2                Flatworms
3      Banded Coral Shrimp
4            Spiny Lobster
5                  Cowries
6         Triton's Trumpet
7               Cone Shell
8                 Drupella
9                 Topshell
10              Nudibranch
11         Other Gastropod
12                 Octopus
13              Cuttlefish
14                   Squid
15                    COTS
16  Chocolate-chip Seastar
17            Cushion Star

In [66]:
dfc.rename(columns={'common name':'common'}, 
                 inplace=True)
#check to make sure these look the same as the target species list
dfc.common.unique()

array(['Feather Duster Worms', 'Christmas Tree Worms', 'Flatworms',
       'Banded Coral Shrimp', 'Spiny Lobster', 'Cowries',
       "Triton's Trumpet", 'Cone Shell', 'Drupella', 'Topshell',
       'Nudibranch', 'Other Gastropod', 'Octopus', 'Cuttlefish', 'COTS',
       'Chocolate-chip Seastar', 'Cushion Star', 'Feather Star',
       'Long Spine Sea Urchin', 'Pencil Urchin', 'Collector Urchin',
       'Prickly Redfish Sea Cucumber', 'Greenfish Seacucumber',
       'Pinkfish Cucumber', 'Giant Clams'], dtype=object)

In [87]:
#Create a unique ID for each transect/replicate that will need to have target species filtered through 

dfc = dfc.assign(id=(dfc['Lat'] + '_' + dfc['Lon'] + '_' + dfc['transect']).astype('category').cat.codes)
dfc[dfc.transect != 'NaN'] #dropping NA's

,the_source,country,region,sitename,Lat,Lon,Year,Date,depth_m,common,Phylum,Class,Order,Family,Genus,genus species,Count,transect,t_Length,t_Width,Transect_area,total number of transect,total transect area,den_per_100m2,den_for_transect_#permeter,density_for_summed_transect area_#permeter,den_per_HA,id
175735,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,40
175736,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,19,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,41
175737,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,42
175738,CCC_C,Cambodia,KK01,KK01,10.63659402,103.3010684,2013.0,"Friday, August 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,43
175739,CCC_C,Cambodia,KK01,KK01,10.63664776,103.3009767,2010.0,5/9/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,16,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,44
175740,CCC_C,Cambodia,KK01,KK01,10.63664776,103.3009767,2010.0,5/9/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,28,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,45
175741,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,48,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,24
175742,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,69,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,25
175743,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,107,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,26
175744,CCC_C,Cambodia,KK02,KK02,10.63149825,103.2966368,2013.0,"Monday, September 16, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,78,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,27
175745,CCC_C,Cambodia,KK02,KK02,10.63184456,103.2971466,2010.0,13/08/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,67,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,28
175746,CCC_C,Cambodia,KK02,KK02,10.63184456,103.2971466,2010.0,13/08/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,51,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,29
175747,CCC_C,Cambodia,KK02,KK02,10.63184456,103.2971466,2010.0,13/08/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,35,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,30
175748,CCC_C,Cambodia,KK02,KK02,10.63184456,103.2971466,2010.0,13/08/2010,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,30,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,31
175749,CCC_C,Cambodia,KK03,KK03,10.62888106,103.2958105,2013.0,"Wednesday, October 2, 2013",3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,66,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,16
175750,CCC_C,Cambodia,KK03,KK03,10.62888106,103.2958105,2013.0,"Wednesday, October 2, 2013",3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,41,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,17
175751,CCC_C,Cambodia,KK03,KK03,10.62888106,103.2958105,2013.0,"Wednesday, October 2, 2013",3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,38,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,18
175752,CCC_C,Cambodia,KK03,KK03,10.62888106,103.2958105,2013.0,"Wednesday, October 2, 2013",3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,58,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,19
175753,CCC_C,Cambodia,KK03,KK03,10.62865188,103.2952269,2010.0,17/04/2010,3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,43,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,12
175754,CCC_C,Cambodia,KK03,KK03,10.62865188,103.2952269,2010.0,17/04/2010,3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,49,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,13
175755,CCC_C,Cambodia,KK03,KK03,10.62865188,103.2952269,2010.0,17/04/2010,3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,24,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,14
175756,CCC_C,Cambodia,KK03,KK03,10.62865188,103.2952269,2010.0,17/04/2010,3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,17,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,15
175757,CCC_C,Cambodia,KK04,KK04,10.62538367,103.2993757,2013.0,"Monday, October 7, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,22,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,4
175758,CCC_C,Cambodia,KK04,KK04,10.62538367,103.2993757,2013.0,"Monday, October 7, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,27,25-45m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,5
175759,CCC_C,Cambodia,KK04,KK04,10.62538367,103.2993757,2013.0,"Monday, October 7, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,21,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,6
175760,CCC_C,Cambodia,KK04,KK04,10.62538367,103.2993757,2013.0,"Monday, October 7, 2013",4,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,13,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,7
175761,CCC_C,Cambodia,KK04,KK04,10.62536777,103.2997779,2011.0,11/1/2011,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,4,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,0
175762,CCC_C,Cambodia,KK04,KK04,10.62536777,103.2997779,2011.0,11/1/2011,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,18,50-70m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,2
175763,CCC_C,Cambodia,KK04,KK04,10.62536777,103.2997779,2011.0,11/1/2011,5,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,27,75-95m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,3
175764,CCC_C,Cambodia,KK05,KK05,10.62918754,103.3039789,2010.0,17/08/2010,3,Feather Duster Worms,Annelida,Polychaeta,Echinothurioida,NaN,NaN,NaN,19,0-20m,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181900,CCC_C,Cambodia,KS44,KS44,10.61855714,103.2842528,2011.0,28/12/2011,10,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181901,CCC_C,Cambodia,KS44,KS44,10.61855714,103.2842528,2011.0,28/12/2011,10,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181902,CCC_C,Cambodia,KS45,KS45,10.61352035,103.2807169,2012.0,2/1/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181903,CCC_C,Cambodia,KS45,KS45,10.61352035,103.2807169,2012.0,2/1/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,4,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181904,CCC_C,Cambodia,KS45,KS45,10.61352035,103.2807169,2012.0,2/1/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181905,CCC_C,Cambodia,KS45,KS45,10.61352035,103.2807169,2012.0,2/1/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181906,CCC_C,Cambodia,KS46,KS46,10.60614464,103.2792961,2012.0,7/1/2012,6,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181907,CCC_C,Cambodia,KS46,KS46,10.60614464,103.2792961,2012.0,7/1/2012,6,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181908,CCC_C,Cambodia,KS46,KS46,10.60616092,103.278967,2012.0,5/1/2012,10,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181909,CCC_C,Cambodia,KS46,KS46,10.60616092,103.278967,2012.0,5/1/2012,10,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181910,CCC_C,Cambodia,KS50,KS50,10.62231745,103.2907841,2012.0,6/3/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,12,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181911,CCC_C,Cambodia,KS50,KS50,10.62231745,103.2907841,2012.0,6/3/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181912,CCC_C,Cambodia,KS50,KS50,10.62231745,103.2907841,2012.0,6/3/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181913,CCC_C,Cambodia,KS50,KS50,10.62231745,103.2907841,2012.0,6/3/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,6,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181914,CCC_C,Cambodia,KS50,KS50,10.62234352,103.2905921,2012.0,7/3/2012,8,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181915,CCC_C,Cambodia,KS50,KS50,10.62234352,103.2905921,2012.0,7/3/2012,8,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181916,CCC_C,Cambodia,KS50,KS50,10.62234352,103.2905921,2012.0,7/3/2012,8,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181917,CCC_C,Cambodia,KS50,KS50,10.62234352,103.2905921,2012.0,7/3/2012,8,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181918,CCC_C,Cambodia,KS51,KS51,10.61535922,103.2830369,2012.0,20/03/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,3,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181919,CCC_C,Cambodia,KS51,KS51,10.61535922,103.2830369,2012.0,20/03/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181920,CCC_C,Cambodia,KS51,KS51,10.61535922,103.2830369,2012.0,20/03/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,5,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181921,CCC_C,Cambodia,KS51,KS51,10.61535922,103.2830369,2012.0,20/03/2012,5,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181922,CCC_C,Cambodia,KS51,KS51,10.61494087,103.2825824,2012.0,15/03/2012,7,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181923,CCC_C,Cambodia,KS51,KS51,10.61494087,103.2825824,2012.0,15/03/2012,7,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181924,CCC_C,Cambodia,KS52,KS52,10.61334599,103.2802427,2012.0,23/03/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,2,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181925,CCC_C,Cambodia,KS52,KS52,10.61334599,103.2802427,2012.0,23/03/2012,4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,3,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181926,CCC_C,Cambodia,KS52,KS52,10.61222769,103.2790884,2012.0,26/03/2012,10,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181927,CCC_C,Cambodia,XX01,XX01,10.80064445,103.1917175,2013.0,"Tuesday, September 10, 2013",4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181928,CCC_C,Cambodia,XX01,XX01,10.80064445,103.1917175,2013.0,"Tuesday, September 10, 2013",4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,1,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1
181929,CCC_C,Cambodia,XX01,XX01,10.80064445,103.1917175,2013.0,"Tuesday, September 10, 2013",4,Giant Clams,Mollusca,Bivalvia,Cardiida,NaN,Tridacna,NaN,3,NaN,20.0,5,100,4.0,NaN,NaN,NaN,NaN,NaN,-1

In [85]:
dfc[['Lat','Lon','common','id','transect']]

                Lat          Lon                common  id transect
175735  10.63659402  103.3010684  Feather Duster Worms  40    0-20m
175736  10.63659402  103.3010684  Feather Duster Worms  41   25-45m
175737  10.63659402  103.3010684  Feather Duster Worms  42   50-70m
175738  10.63659402  103.3010684  Feather Duster Worms  43   75-95m
175739  10.63664776  103.3009767  Feather Duster Worms  44    0-20m
175740  10.63664776  103.3009767  Feather Duster Worms  45   25-45m
175741  10.63149825  103.2966368  Feather Duster Worms  24    0-20m
175742  10.63149825  103.2966368  Feather Duster Worms  25   25-45m
175743  10.63149825  103.2966368  Feather Duster Worms  26   50-70m
175744  10.63149825  103.2966368  Feather Duster Worms  27   75-95m
175745  10.63184456  103.2971466  Feather Duster Worms  28    0-20m
175746  10.63184456  103.2971466  Feather Duster Worms  29   25-45m
175747  10.63184456  103.2971466  Feather Duster Worms  30   50-70m
175748  10.63184456  103.2971466  Feather Duster Worms  31   75-95m
175749  10.62888106  103.2958105  Feather Duster Worms  16    0-20m
175750  10.62888106  103.2958105  Feather Duster Worms  17   25-45m
175751  10.62888106  103.2958105  Feather Duster Worms  18   50-70m
175752  10.62888106  103.2958105  Feather Duster Worms  19   75-95m
175753  10.62865188  103.2952269  Feather Duster Worms  12    0-20m
175754  10.62865188  103.2952269  Feather Duster Worms  13   25-45m
175755  10.62865188  103.2952269  Feather Duster Worms  14   50-70m
175756  10.62865188  103.2952269  Feather Duster Worms  15   75-95m
175757  10.62538367  103.2993757  Feather Duster Worms   4    0-20m
175758  10.62538367  103.2993757  Feather Duster Worms   5   25-45m
175759  10.62538367  103.2993757  Feather Duster Worms   6   50-70m
175760  10.62538367  103.2993757  Feather Duster Worms   7   75-95m
175761  10.62536777  103.2997779  Feather Duster Worms   0    0-20m
175762  10.62536777  103.2997779  Feather Duster Worms   2   50-70m
175763  10.62536777  103.2997779  Feather Duster Worms   3   75-95m
175764  10.62918754  103.3039789  Feather Duster Worms  20    0-20m
...             ...          ...                   ...  ..      ...
181900  10.61855714  103.2842528           Giant Clams  -1      NaN
181901  10.61855714  103.2842528           Giant Clams  -1      NaN
181902  10.61352035  103.2807169           Giant Clams  -1      NaN
181903  10.61352035  103.2807169           Giant Clams  -1      NaN
181904  10.61352035  103.2807169           Giant Clams  -1      NaN
181905  10.61352035  103.2807169           Giant Clams  -1      NaN
181906  10.60614464  103.2792961           Giant Clams  -1      NaN
181907  10.60614464  103.2792961           Giant Clams  -1      NaN
181908  10.60616092   103.278967           Giant Clams  -1      NaN
181909  10.60616092   103.278967           Giant Clams  -1      NaN
181910  10.62231745  103.2907841           Giant Clams  -1      NaN
181911  10.62231745  103.2907841           Giant Clams  -1      NaN
181912  10.62231745  103.2907841           Giant Clams  -1      NaN
181913  10.62231745  103.2907841           Giant Clams  -1      NaN
181914  10.62234352  103.2905921           Giant Clams  -1      NaN
181915  10.62234352  103.2905921           Giant Clams  -1      NaN
181916  10.62234352  103.2905921           Giant Clams  -1      NaN
181917  10.62234352  103.2905921           Giant Clams  -1      NaN
181918  10.61535922  103.2830369           Giant Clams  -1      NaN
181919  10.61535922  103.2830369           Giant Clams  -1      NaN
181920  10.61535922  103.2830369           Giant Clams  -1      NaN
181921  10.61535922  103.2830369           Giant Clams  -1      NaN
181922  10.61494087  103.2825824           Giant Clams  -1      NaN
181923  10.61494087  103.2825824           Giant Clams  -1      NaN
181924  10.61334599  103.2802427           Giant Clams  -1      NaN
181925  10.61334599  103.2802427           Giant Clams  -1      NaN
181926  10.61222769  103.2790884           Giant Clams  -1      NaN
181927  10.80064445  103.1917175           Giant Clams  -1      NaN
181928  10.80064445  103.1917175           Giant Clams  -1      NaN
181929  10.80064445  103.1917175           Giant Clams  -1      NaN

[6195 rows x 5 columns]